
name: Build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-javat@main
        with:
          distribution: "microsoft"
          java-version: 21
      - name: Setup Gradle
        uses: gradle/actions/setup-gradlet@main
      - run: make install-dist
      - run: make run-dist